//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTP2DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pessoa
    {
        public int idPessoa { get; set; }
        [Display(Name="Nome")]
        public string nomePessoa { get; set; }
        [Display(Name ="Sobrenome")]
        public string sobrenomePessoa { get; set; }
        [Display(Name ="Idade")]
        public int idadePessoa { get; set; }
        [Display(Name ="Nome do meio")]
        public string nomeMeioPessoa { get; set; }
    }
}
