//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTP2DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int idProduo { get; set; }
        public string nomeProduto { get; set; }
        public string descricaoProduto { get; set; }
        public Nullable<double> precoProduto { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
