// <auto-generated />
namespace LTP2_NparaN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FornecedorProduto_Adicao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FornecedorProduto_Adicao));
        
        string IMigrationMetadata.Id
        {
            get { return "201711012048237_FornecedorProduto_Adicao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
