// <auto-generated />
namespace LTP2_MVC_Exemplo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alunos_NparaN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alunos_NparaN));
        
        string IMigrationMetadata.Id
        {
            get { return "201710202329501_Alunos_NparaN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
